name: TWRP 16 Builder

on:
  workflow_dispatch:
    inputs:
      TWRP_MANIFEST_URL:
        description: "TWRP manifest url"
        required: true
        default: "https://github.com/TWRP-Test/platform_manifest_twrp_aosp"

      TWRP_MANIFEST_BRANCH:
        description: "TWRP branch"
        required: true
        default: "twrp-16.0"

      DEVICE_TREE_URL:
        description: "Device tree url"
        required: true
        default: "https://github.com/DrBrown28/twrp_device_Meteoid_sm8735.git"

      DEVICE_TREE_BRANCH:
        description: "Device tree branch"
        required: true
        default: "twrp-16.0"

      DEVICE_PATH:
        description: "Device path"
        required: true
        default: "nothing/Metroid"

      DEVICE_NAME:
        description: "Device name"
        required: true
        default: "Metroid"

      BUILD_PARTITION:
        description: "Build partition"
        required: true
        default: "recovery"

jobs:

  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main


    - name: Setup environment
      run: |
        sudo apt update
        sudo apt install -y repo git ccache python3 bc \
        build-essential libssl-dev libelf-dev


        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"


    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: twrp16
        max-size: 10G


    - name: Initialize source
      run: |

        repo init \
        -u ${{ github.event.inputs.TWRP_MANIFEST_URL }} \
        -b ${{ github.event.inputs.TWRP_MANIFEST_BRANCH }} \
        --depth=1


    - name: Sync source
      run: |

        repo sync \
        -j$(nproc --all) \
        --force-sync \
        --no-clone-bundle


    - name: Setup device tree
      run: |

        rm -rf device/${{ github.event.inputs.DEVICE_PATH }}

        git clone \
        -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} \
        ${{ github.event.inputs.DEVICE_TREE_URL }} \
        device/${{ github.event.inputs.DEVICE_PATH }}


    - name: Verify device tree
      run: |

        echo "===== DEVICE TREE ====="

        ls -la device/${{ github.event.inputs.DEVICE_PATH }}

        echo "===== PRODUCTS ====="

        cat device/${{ github.event.inputs.DEVICE_PATH }}/AndroidProducts.mk

        echo "===== MK FILES ====="

        ls device/${{ github.event.inputs.DEVICE_PATH }}/*.mk


    - name: Build TWRP
      run: |

        source build/envsetup.sh

        export ALLOW_MISSING_DEPENDENCIES=true

        export USE_CCACHE=1

        export CCACHE_EXEC=$(which ccache)


        lunch twrp_${{ github.event.inputs.DEVICE_NAME }}-eng


        m ${{ github.event.inputs.BUILD_PARTITION }}image \
        -j$(nproc --all)


    - name: Check output
      run: |

        ls -lh \
        out/target/product/${{ github.event.inputs.DEVICE_NAME }}/


    - name: Upload recovery
      uses: actions/upload-artifact@v4
      with:

        name: TWRP-${{ github.event.inputs.DEVICE_NAME }}

        path: |
          out/target/product/${{ github.event.inputs.DEVICE_NAME }}/*.img
